### ISSUE TITLE
Fixed elements are removed when opening the Drawer

### ISSUE THREAD

**Issue by revogabe** [emilkowalski/vaul#143]
When having other fixed elements active on my screen, when activating the Drawer it ends up hiding the fixed and when closing it reappears, is there any way I can open the drawer without removing the fixed elements from the screen?

Preview: 

https://github.com/emilkowalski/vaul/assets/56942108/a3a48912-71c6-44ad-a870-6396e48e7c14

**Comment by emilkowalski** [comment]
Are these sticky or fixed? Sticky elements will disappear as the body has position fixed as long as the drawer is open to avoid iOS bugs. If yours is fixed and you still experience that issue, please provide a codesandbox demo.

**Comment by revogabe** [comment]
are fixed, I will produce a test in codesandbox to analyze

**Comment by nytrek** [comment]
I have the same issue

**Comment by jordant97** [comment]
I think i found the solution, you need to change min-h-[100vh] to h-screen in layout.tsx. From my own test, i found out that when the drawer is open, my page will resort back to the content height even if i set the page div to h-full, might be related to vaul adding css to the parent element to make the whole thing work


[Codesandbox](https://codesandbox.io/p/devbox/drawer-with-scale-forked-cwcf37?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clnqz6o1600093b6jv0s3frkg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clnqz6o1500043b6jr2r16hcg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clnqz6o1500063b6j4ksglbkn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clnqz6o1500083b6jplb8j2id%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.512521457181904%252C44.487478542818096%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clnqz6o1500043b6jr2r16hcg%2522%253A%257B%2522id%2522%253A%2522clnqz6o1500043b6jr2r16hcg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clnqz6o1500083b6jplb8j2id%2522%253A%257B%2522id%2522%253A%2522clnqz6o1500083b6jplb8j2id%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnqz6o1500073b6jfc8dmaga%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clnqz6o1500073b6jfc8dmaga%2522%257D%252C%2522clnqz6o1500063b6j4ksglbkn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clnqz6o1500053b6jbcrr0vck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clnqz6o1500063b6j4ksglbkn%2522%252C%2522activeTabId%2522%253A%2522clnqz6o1500053b6jbcrr0vck%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10%257D)

**Comment by emilkowalski** [comment]
Please use @jordant97' solution.

**Comment by mannol** [comment]
This still seems to be an issue, the proposed solution by @jordant97 doesn't do the trick. [The Sandbox here](https://github.com/emilkowalski/vaul/pull/209#issuecomment-1911288166) reproduces it.

The problem lies in the fact that drawer changes the `body.style.top` to be the current scroll offset at trigger, which helps the animation but, the issue is, children elements that have position: 'fixed' aren't aware of the change, so therefore they are shown relative to the body.

![image](https://github.com/emilkowalski/vaul/assets/13100554/846ca01d-03eb-4881-a12b-dffe7224d764)

This can be fixed by changing the offset of the child elements when changing body.

Also, thanks for this awesome package and your hard work! 🙏

**Comment by Andrii-Antoniuk** [comment]
Hello @emilkowalski!

I was curious whether @mannol suggestion could be implemented, as this issue is marked as closed while it's not solved :)

**Comment by felixpackard** [comment]
Hey @emilkowalski, thanks for the awesome library!

Just wanted to mention that issue is affecting me as well. The issue with the solution proposed by @jordant97 is that, while it does prevent fixed elements from going off the screen when the drawer opens, it also makes the div scrollable rather than the body, which results in other issues, such as:

- The scrollbar rendering underneath fixed elements such as navigation
- On macOS you don't get the same rubber-band animation when you scroll to the end of a div as you do when you scroll to the end of the body
- Any code that relies on `window.scrollY` will break

I expect there may be other differences between overflow on the body and a div that I'm yet to come across.

One idea I had to fix this is a data attribute such as `data-vaul-fixed` that could be used to let vaul know which elements should have position style overridden when the drawer is open.

Until this is fixed I may have to resort to using the library without background scaling as I haven't found any other workarounds yet. Hopefully this issue can be re-opened as the background scaling looks really nice!

**Comment by kamami** [comment]
Why is this closed? This is still an issue.

**Comment by SimonVillage** [comment]
@emilkowalski is there a fix planned for this? The issue still exists.

**Comment by bim-oulabi** [comment]
Still an issue, using height:100vh breaks the behavior that it starts the screen from top as well
