### ISSUE TITLE
bug(ios): can't zoom out when drawer is open, url bar hides bottom content

### ISSUE THREAD

**Issue by juliusmarminge** [emilkowalski/vaul#215]
I've noticed that after Safari has zoomed in (if font size < 16px), there is no way to zoom back out when the drawer is open.

There also seems to be a bit of lag when the keyboard comes up / goes away, maybe that's my device  (iPhone 12) being too slow but thought I'd bring it up

Lastly, when the URL bar is open, the content goes underneath and there doesn't seem to be a way to access that content anymore, is this a user-land concern that I should handle on my end or should Vaul handle this internally?

Video: 

<video src="https://github.com/juliusmarminge/time-report/assets/51714798/c262be21-b1f2-410d-b1ab-07abe0a4bed2" />

Source: https://github.com/juliusmarminge/time-report/blob/56f8c78574702a757a08872145cc697ca553c296/src/app/(app)/report/%5Bmonth%5D/_components/report-time-form.tsx#L209

**Comment by juliusmarminge** [comment]
For a simpler example, see https://ui.shadcn.com/docs/components/drawer#responsive-dialog

It's also very buggy when interacting with the form inside the drawer

**Comment by emilkowalski** [comment]
Thank you for reporting.

1. I highly recommend keeping your input's font-size on mobile at 16px, that's what we do at Vercel as well for example and that will fix the issue described. Anything smaller is bad UX as well because of the zoom in my opinion.
2. I can't play the video for some reason, but the lag is most certainly not due to Vaul as it doesn't influnece how the keyboard comes up or down.
3. I can't see the video unfortunately haha, please ping me once it's working again

**Comment by juliusmarminge** [comment]
https://github.com/emilkowalski/vaul/assets/51714798/99aa50ea-224f-4e41-ae66-70b81caab5af

how about now @emilkowalski

**Comment by emilkowalski** [comment]
Works now! My guess is that all of the issues will be gone once you make the input have a font size of 16px.

**Comment by emilkowalski** [comment]
Did that solve the issue @juliusmarminge

**Comment by juliusmarminge** [comment]
yes - sorry for not reporting back!
