### ISSUE TITLE
Text inside drawer component is not draggable for copying

### ISSUE THREAD

**Issue by suhjohn** [emilkowalski/vaul#295]
Hi, I expect the cursor to change when I hover on top of a p tag inside Drawer.Content. 
I want to be able to drag on the text so that I can copy it. This doesn't seem to work whether dismissible={false} or not. 
What can I do to fix this?

I played around on the console and I see that removing "vaul-drawer" on the top level fixes the issue. Is that necessary?

**Comment by emilkowalski** [comment]
It's unclear what you what to achieve to me, can you clarify?

**Comment by naufalfarras** [comment]
we might want to copy and paste the text inside the drawer, instead when we want to drag to select the text, it is dragging the entire drawer (text was not selected)

**Comment by anstiwar** [comment]
To copy text from the Drawer component we need to set the user-select to text instead of none. tried this using the browser developer mode and able to copy the text , but not sure how to apply this via my component code directly. 

![image](https://github.com/emilkowalski/vaul/assets/19320565/d83ac127-a636-4fa3-a840-8bf1ab98e67b)
