### ISSUE TITLE
NextUI Select cannot be scrolled

### ISSUE THREAD

**Issue by bertdida** [emilkowalski/vaul#301]
I am trying to have a NextUI Select component inside the drawer https://nextui.org/docs/components/select#usage

But I am having an issue, where the list cannot be scrolled
https://codesandbox.io/p/devbox/nextui-select-inside-vaul-rq86tk?file=%2Fapp%2Fmy-drawer.tsx%3A7%2C15

**Comment by SaadFarooq-Dev** [comment]
Hey @bertdida  did you find the issue? I cannot even  click on the select dropdown list.

**Comment by emilkowalski** [comment]
That's because this select component renders in a portal which is outside of the drawer by definition. The solution here is to not render it in a portal.

**Comment by jimmailcamp** [comment]
> That's because this select component renders in a portal which is outside of the drawer by definition. The solution here is to not render it in a portal.

Is there anything at all you may be aware of that can make this work?
Since it's not possible for both nextui and semantic-ui-react to have the select inputs working without use of a portal.
Could you explain why the scrolling behaviour on the select's listbox gets prevented when in the drawer?

The clicks etc I got working, even in the portal. Only scrolling the listboxes seems impossible.

Unfortunately I can not switch to a different Ui element. I'm affraid I have to swap out the drawer to make this work otherwise.

**Comment by jimmailcamp** [comment]
Hi!
Managed to solve the issue @bertdida @SaadFarooq-Dev 

Within the Drawer.Content assign a ref to any div within.
Pass the ref to the select's popoverProps.portalContainer.

Now the select's popover is a direct child of the Drawer!

Also make sure you apply '!pointer-events-auto ' as a className to the popoverContent in the classNames prop.

Now everything works as expected.
