### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server when using Drawer from vaul in Nextjs 13

### ISSUE THREAD

**Issue by rahXephonz** [emilkowalski/vaul#351]
<img width="1116" alt="Screenshot 2024-05-14 at 20 16 50" src="https://github.com/emilkowalski/vaul/assets/77242429/029e2a14-d48b-4b18-b5e5-363ef3a43418">

```bash
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Root (file://clients/web/node_modules/.pnpm/vaul@0.9.1_@types+react-dom@18.2.0_@types+react@18.2.0_react-dom@18.2.0_react@18.2.0/node_modules/vaul/dist/index.mjs:749:23)
    at Drawer
```

i have use shadcn drawer and i believe its extending vaul in the components.
so i have this error in every page or component that using Drawer from Vaul

Is there any solutions to supress this warning?

**Comment by Hung-Yeung** [comment]
I am using remix.run which is also a full stack framework based on React.
To fix this issue i added this line of code
`if (typeof window == "undefined") return null;`
When React components are rendered on the server, they do not have access to browser-specific globals like window, document, etc., because these are only available in the browser environment.
If a React component relies on window, document, or any other browser-specific API, trying to access them during SSR will cause errors since these do not exist on the server.
The line is a simple check to determine if the code is running on the server (where window is undefined). If it is, the component returns null, effectively skipping the rendering of that component on the server.

**Comment by MinhLeeBtaskee** [comment]
Because we cannot measure the layout before repainting the screen in the Server side rendering
We need to replace `useLayoutEffect` with `useEffect`.

Make Drawer return null, like: `if (typeof window == "undefined") return null;`
will miss the original target since we are aiming for SSR

I see issue fixed at **https://github.com/emilkowalski/vaul/pull/368/files** by
`export const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;`

Please release soon 📆

**Comment by rahXephonz** [comment]
Thank you @emilkowalski
