### ISSUE TITLE
Anchor tag hyperlink to page fragments not working

### ISSUE THREAD

**Issue by AuJezus** [emilkowalski/vaul#352]
When using <a> with href='#id', the url gets set correctly, but it doesn't scroll to the element with #id. If you close the drawer and press the same link outside the drawer it works.

I think it might be an issue with some kind of overlay and the browser can't find ids. Is there any workaround for this?

**Comment by matiasmarcodelpont** [comment]
Having the same issue

**Comment by moonhee0507** [comment]
I had the same problem as you and it was solved through this:

#https://github.com/shadcn-ui/ui/issues/3536#issuecomment-2138995083

As stated in the original solution, it seems to be a trick method rather than a fundamental solution.

`hashchange` event -> Save `hash` state -> Scroll after 500ms

Maybe it will help you.

**Comment by emilkowalski** [comment]
This should be fixed in #406
