### ISSUE TITLE
body scroll delay after closing

### ISSUE THREAD

**Issue by sgrund14** [emilkowalski/vaul#64]
noticing a delay in body scrollability after closing the drawer, maybe a half second or so

https://github.com/emilkowalski/vaul/assets/14083701/ec1552ee-4a1e-42e7-ae56-5daf5b6bdc92

pictured: after the first close of the menu, I try to scroll the body and it is locked. after the second, i wait half a second, and it works.

is there a setting I can pass to decrease this threshold? noticed there was `scrollLockThreshold` but that looks like it's more for the content inside the drawer instead of the scroll lock on the body content

**Comment by emilkowalski** [comment]
So you are trying to scroll right after you close it, without waiting for the animation to end. Is that what happens here?
How it works today is that overflow hidden is removed _after_ the animation ends, which is not ideal. I'll work on fixing it so that you can scroll without waiting for the animation to end.

**Comment by sgrund14** [comment]
Yeah exactly, although it seems like the animation has ended by the time I'm trying to scroll. For the quick trigger scrollers amongst us it gets blocked. Thanks for checking it out!

**Comment by emilkowalski** [comment]
Should be fixed in #67. Feel free to re-open if you still experience this after the new version comes out.

**Comment by sgrund14** [comment]
lovely, thanks @emilkowalski
